### ISSUE TITLE
Nothing happens with Fetch PMCID Zotero 7

### ISSUE THREAD

**Issue by jessicadlang** [retorquere/zotero-pmcid-fetcher#12]
Hi,
I'm looking forward to saving a lot of time with this tool! I have dragged the .xpi for version 0.0.28 and can see the "Fetch PMCID" when I right click on an item. However, nothing gets fetched into the "Extra" field of the citation. No popups either. I had originally imported the references with the magic want tool from their DOI, so the doi field is complete (short version). I am using Zotero 7.0.0-beta.54+6b996d4f9 in case that helps.

**Comment by jessicadlang** [comment]
Oh, just found the fix: I set `extensions.zotero.pmcid.tags` to `FALSE`, and now it all works

**Comment by retorquere** [comment]
I'm not sure the short doi works (would depend on the API I'm calling, I don't do anything with the doi but pass it to the api), and I'm surprised the tags preference makes a difference here, but if it works for you I'm not complaining.

**Comment by jessicadlang** [comment]
I wasn't getting that pop-up mentioned the first time, so maybe it was hidden somewhere and it couldn't get past the first request without selecting something? Just a guess. I'm on a Mac (M1) too, in case that matters.

**Comment by retorquere** [comment]
Processor doesn't matter; I'm on M2, but nothing of the platform is OS or processor dependent. The pop-up can't hide behind Zotero, if you can see Zotero and the popup is active, it is front of Zotero. But if `tags` is set to `true` or `false`, the popup doesn't show.

**Comment by wschmidt96** [comment]
Hello, just wanted to say that I was experiencing the same issue, and setting `tags` to `false` was also able to resolve it for me as well.

**Comment by retorquere** [comment]
I must admit I don't fully grok what's going wrong in your cases. What isn't working exactly?

**Comment by wschmidt96** [comment]
In my case when I would Fetch PMCIDs on selected items it would do one of two things:
1. If there is no PMID/PMCID associated with the DOI it will throw the error popup like it is supposed to.
2. If there is a PMID then it will just hang, it is unable to update the Extra field with the information and there's no indication that it even performed the fetch.

If I had to guess the issue is probably either in the updating of the Extra field or in the check on whether to add as a tag or not. I noticed that I did not have a `extensions.zotero.pmcid.tags` variable before finding this thread, but creating one and setting it to `False` just like jessicadlang suggested seemed to fix the problem and the program was able to write into Extra like normal.

I hope that this information helps, I'm a big fan of your plugin and it is an absolute lifesaver when working on grant writing. Please let me know if there's anything else I can tell you to help!

**Comment by retorquere** [comment]
Do you have a DOI I can test this with?

**Comment by retorquere** [comment]
found it. new version is out.
